### ISSUE TITLE
No notification anymore using push.humhub.com

### ISSUE THREAD

**Issue by funkycram** [humhub/fcm-push#23]
Tested with 2 instances and 2 devices (mobile and desktop).
Was working well before.

Module version 2.0.0-beta.1
Method: Push Service (Beta) with https://push.humhub.com/site/index

**Comment by luke-** [comment]
@funkycram Hmm, push notification with the last app version via push.humhub.com still works for me. I'll keep investigating, there may be a problem here with the FCM Push Module.

**Comment by ArchBlood** [comment]
I'm also not having any issues with the push services, it's rather strange that it works for some but not all, possible PHP extension missing?

**Comment by funkycram** [comment]
Thanks for your answers.
Tested with the [Community instance](https://community.humhub.com/) and 2 others on Android, Chrome, Brave, Linux and Windows OS, I don't receive the notifications anymore. Tested also to reinstall the module.
In all my tests, I made it work twice with a comment, nether with "Like".
Mobile is checked on my account:
![image](https://github.com/humhub/fcm-push/assets/23310825/db78cd74-c245-4518-8135-eaf39c04783f)

If everything's working well on your side, I'll close the issue. Maybe a problem on my side.
But in that case, I don't know how to solve https://github.com/humhub/app/issues/87 and https://github.com/humhub/app/issues/86

**Comment by luke-** [comment]
@funkycram I currently have problems here as well and am currently testing.

With the FCM Push module version Beta.3 there is a link "Mobile App Debug" in the module settings at the very bottom right.

On this page you can trigger test notifications, view a list of devices push tokens registered for the current user and force the app to re-register the push token.

But currently I don't get push notifications either.

**Comment by funkycram** [comment]
Thanks. Nice to have a debug option!
I'll try to take more time for testing as soon as possible (not sure when).

**Comment by luke-** [comment]
@funkycram I'm working on this right now, I'll let you know as soon as I have any new findings.

**Comment by luke-** [comment]
@funkycram If you have time, please try it again with the latest app version (.63) and the FCM Push module (Beta4). Thanks!

**Comment by luke-** [comment]
@funkycram Thanks for testing. I've just released fcm push beta 5 which should solve the problem.

**Comment by funkycram** [comment]
Thanks @luke- 
I've tested again and I still cannot make push notification work (Browser and app) with Humhub 1.14.2 and fcm push beta 5 (Install Id starts with 66a07341).
If you think the problem is on my side, I'll test more with the Community instance and another Humhub instance (developer branch).

**Comment by funkycram** [comment]
Tested on Humhub develop branch latest version. No notification. I cannot make work anything on the debug page:
![image](https://github.com/humhub/fcm-push/assets/23310825/97bf00fa-60f1-41ab-97b0-7fa18a5c4389)

An idea of what I should do?
My settings:
![image](https://github.com/humhub/fcm-push/assets/23310825/f5f2a380-e7c3-4e3d-9ca3-487c6fe9930d)

**Comment by luke-** [comment]
@funkycram Thanks for the details.

It is important to note that our push service only works for the mobile app and NOT for the browser notifications.

The mobile app should always automatically register a push token after a user login (with the current FCM module).
So please try to log out of the app and log in again.

After that the message "No regsitered Push Tokens should disappear"

**Comment by funkycram** [comment]
Oh, sorry, I didn't take time to read that the Push service was only for the mobile app...
Maybe we could rename the titles?
- Push Service (Beta) -> Push Service for mobile app (Beta)
- Firebase Cloud Messaging -> Firebase Cloud Messaging for browser notifications

However, I had also tried with the mobile app v1.0.63 on Android 10 and I tried again now with Humhub 1.14.2 and Humhub develop branch latest version. I always have "App Detection - Current Request: NO App Request Detected" even just after a user login.

I've tested also with the Community instance: notifications works well, I receive them via the mobile app.

I noticed that (not sure it can explain the problem):
- With Humhub develop and SSO (Keycloak) login: just after coming back from Keycloak login page, a page with an error flashes (I have no time to read the text or make a screenshot) and then I'm logged in correctly to Humhub
- With Humhub 1.14 and basic authentification, and with the Community instance, after submitting the Humhub instance URL, sometimes the app crashes and sometimes I'm back to the Humhub instance URL form and I have to submit again. 
- With the Community: I had an app crash just after login in.

**Comment by funkycram** [comment]
So now I've understand that we need both Push service AND Firebase, I've tested again with Firebase configured and I receive the mobile notifications well now.

So new title suggestions:
- Push Service (Beta) -> Push Service (required for the mobile app) (Beta)
- Firebase Cloud Messaging -> Firebase Cloud Messaging (required for mobile notifications)

The app behavior is alright: when closing / reopening the app, I stay logged in, and if I log out I can change the URL of the Humhub instance.

But strangely, I still have "App Detection - Current Request: NO App Request Detected" even after user login.

If I click on the "Trigger "HumHub Update" notification" button it works well, but if I click on other buttons, I have "Could not send message! ..."

**Comment by luke-** [comment]
> So now I've understand that we need both Push service AND Firebase, I've tested again with Firebase configured and I receive the mobile notifications well now.
> 
> So new title suggestions:
> 
> * Push Service (Beta) -> Push Service (required for the mobile app) (Beta)
> * Firebase Cloud Messaging -> Firebase Cloud Messaging (required for mobile notifications)
> 
Ok good point!

> But strangely, I still have "App Detection - Current Request: NO App Request Detected" even after user login.
> 
> If I click on the "Trigger "HumHub Update" notification" button it works well, but if I click on other buttons, I have "Could not send message! ..."

If you using the App, the App Detection says "NO App request Detected"? Maybe it's also a bit misleading. It checks if the current requests comes from the mobile app.

**Comment by funkycram** [comment]
OK, so everything's fine now!
I haven't seen you've already renamed the titles... But https://github.com/humhub/fcm-push/issues/26 can still be useful for the changelog and the conversion from links to buttons because the first time we see this config page it's not obvious the links are cliquables (because of the black color and in a list).
